import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { NextIntlClientProvider, useLocale } from "next-intl";
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  const locale = useLocale();
  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale} data-theme="light">
      <body className={inter.className}>
        <Providers>
          <NextIntlClientProvider locale={locale}>
            <div className="bg-gradient-to-r w-full overflow-x-hidden scroll-smooth from-[#D1E8FF] to-[#F5FAFF] dark:from-[#1E2833] dark:to-[#1C2023]">
              {children}
            </div>
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
